module.exports = {
    ERR_HEADER_PARAMETERS:     {code: '1001' ,msg: '缺少头部参数，请稍后重试'},
    ERR_INVALID_CHANNEL:       {code: '1002' ,msg: '未授权接口调用者'},
    ERR_INVALID_UUID:          {code: '1003' ,msg: '未获取到UUID'},
    ERR_SYSTEM_DB:             {code: '1004' ,msg: '网络或者服务器异常，请稍后重试'},
    ERR_MISS_PARAMETERS:       {code: '1005', msg: '缺少参数或者参数格式不正确' },
    ERR_DATABASE_CONNECTION:   {code: '1006', msg: '数据库异常，请稍后重试'},
    ERR_CODE_EXPIRED:          {code: '1006' ,msg: '验证码已经过期'},

    ERR_INVALID_CODE_TYPE:     {code: '2001', msg: '无效的验证码类型'},
    ERR_FORMAT_PHONE:          {code: '2002' ,msg: '手机号格式不正确'},
    ERR_FORMAT_EMAIL:          {code: '2003' ,msg: '邮箱地址格式不正确'},
    ERR_SEND_VERIFY_CODE:      {code: '2004', msg: '验证码发送失败'},
    ERR_PHONE_OR_EMAIL_DIFF:   {code: '2005' ,msg: '验证码接收地址与填写地址不一致'},
    ERR_VERIFY_EXPIRED:        {code: '2006' ,msg: '验证码已经过期'},
    ERR_INVALID_CODE:          {code: '2007' ,msg: '无效验证码'},
    ERR_MISS_IMG_CODE:         {code: '2008', msg: '缺少验证码参数'},
    ERR_MAX_VERIFY_TIMES:      {code: '2009', msg: '验证码错误次数累计超过限制'},
    OK_SEND_CODE:              {code: '0',    msg: '验证码发送成功'},
    OK_VERIFY_CODE:            {code: '0',    msg: '验证码正确' },
    ERR_FORMAT_PASSWORD:       {code: '2010', msg:'密码格式不正确'},
    ERR_FORMAT_NICKNAME:       {code: '2011', msg:'昵称格式不正确'},

    ERR_USER_EXISTS:           {code: '3001' ,msg:'手机号或者邮箱已经存在'},
    ERR_USER_NOT_EXISTS:       {code: '3002', msg:'账号不存在' },
    ERR_NOT_LOGIN:             {code: '3003', msg:'请登陆后重试'},
    
    OK_SET:                    {code: '0',    msg: '设置成功' },
    ERR_SET:                   {code:'4001',  msg:'设置失败'},
    SET_TRADE_PASSWORD:        {code:'4002',  msg:'请先设置交易密码'},
    TRADE_PASSWORD_NOTNULL:    {code:'4003',  msg:'交易密码已存在' },
    OK_TO_GET:                 {code: '0',    msg: '查询成功' },
    ERR_TO_GET:                {code: '4004', msg: '查询失败' },
    
    OK_TO_UPLOAD:              { code: '0',   msg: '上传成功' },
    ERR_TO_UPLOAD:             { code: '5001',msg: '上传失败' },
    ERR_TYPE_OF_FILE:          { code: '5002',msg: '文件类型不正确'},
    OK_TO_APPLY:               { code: '0',   msg: '申请成功' },
    ERR_TO_APPLY:              { code: '5003',msg: '申请失败' },

    UNDEFINED_USER:            {code: '8000', msg: '未找到该用户' },
    OK_REGISTERED:             {code: '0',    msg: '注册成功' },
    ERR_REGISTERED:            {code: '8001', msg: '注册失败' },
    OK_TO_LOGIN:               {code: '0',    msg: '登录成功' },
    ERR_LOGIN:                 {code: '8002', msg: '登录失败' },
    INCORRCT_USERNAME_PWD:     {code: '8003', msg:'用户名或密码错误'},
    SAME_PARAMETER:            {code: '8004', msg:'新密码与原密码相同'},
    OK_TO_LOGOUT:              {code: '0',    msg: '退出成功' },
    OK_USER_INFO:              {code: '0',    msg: '获取用户信息成功' },
    UNDEFINED_USER_APPLY:      {code:'8005',  msg:'未找到该用户申请信息'},
    

    WAR_NETWORK_CHANGE:        {code: '9001', msg: '检测到网络发生变化'},
    ERR_FORMAT_TRADE_PWD:      {code: '9002', msg: '资产密码格式不正确'},
    ERR_FORMAT_WALLET:         {code: '9003', msg: '钱包地址非法'},
    ERR_MEMO_MAX_LENGTH:       {code: '9004', msg: '转账备注信息过长'},
    ERR_FORMAT_AMOUNT:         {code: '9005', msg: '数量格式不正确'},
    telINSUF_FUND:             {code: '9006', msg: '支付余额不足'},
    tecNO_DST_INSUF_SWT:       {code: '9007', msg: '账号不存在'},
    ERR_PAYMENT:               {code: '9008', msg: '转账失败,请重新再试'},
    OK_CREATE_WALLET:          {code: '0',    msg: '成功创建钱包' },
    ERR_MISS_WALLET:           {code: '9009', msg: '创建钱包失败' },
    OK_PAYMENT:                {code: '0',    msg: '转账成功'},
};